# Generated by Django 4.2.3 on 2023-09-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='option',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
