# Generated by Django 4.2.3 on 2023-09-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_course_option_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='option',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
