# Generated by Django 4.2.3 on 2023-09-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_name_mentor_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='title',
            new_name='name',
        ),
    ]
