# Generated by Django 4.2.3 on 2023-09-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_title_mentor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
