# Generated by Django 4.2.3 on 2023-09-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_mentor_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
