# Generated by Django 4.2.3 on 2023-09-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_urls'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='urls',
            new_name='Url',
        ),
    ]
