# Generated by Django 4.2.3 on 2023-10-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_rename_urls_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='icon',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
