# Generated by Django 4.2.3 on 2023-10-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_footerlink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FooterLink',
            new_name='FooterLinkPages',
        ),
    ]
