# Generated by Django 4.2.3 on 2023-10-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_rename_footerlink_footerlinkpages'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='FooterLinkPages',
            new_name='FooterLinkBlog',
        ),
    ]
